//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PublicTools.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission.
        /// </summary>
        public static string Error_Accessdenied {
            get {
                return ResourceManager.GetString("Error_Accessdenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not assign godadmin role.
        /// </summary>
        public static string Error_AddGodAdminRole {
            get {
                return ResourceManager.GetString("Error_AddGodAdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record is used, Please Inactive it.
        /// </summary>
        public static string Error_DataWasUsed {
            get {
                return ResourceManager.GetString("Error_DataWasUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model is empty.
        /// </summary>
        public static string Error_EmptyList {
            get {
                return ResourceManager.GetString("Error_EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Was Not Found!.
        /// </summary>
        public static string Error_FaildToFindProduct {
            get {
                return ResourceManager.GetString("Error_FaildToFindProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry  assign role to role was  failed.
        /// </summary>
        public static string Error_FailedToAssignRoleToUser {
            get {
                return ResourceManager.GetString("Error_FailedToAssignRoleToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process was failed..
        /// </summary>
        public static string Error_FailProcess {
            get {
                return ResourceManager.GetString("Error_FailProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object was not found.
        /// </summary>
        public static string Error_FailToFindObject {
            get {
                return ResourceManager.GetString("Error_FailToFindObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete or update Godadmin role!.
        /// </summary>
        public static string Error_GodAdminRole {
            get {
                return ResourceManager.GetString("Error_GodAdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete GodAdmin user.
        /// </summary>
        public static string Error_GodAdminUser {
            get {
                return ResourceManager.GetString("Error_GodAdminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid sellerId.
        /// </summary>
        public static string Error_IncorrectSellerId {
            get {
                return ResourceManager.GetString("Error_IncorrectSellerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid or active parentid..
        /// </summary>
        public static string Error_InValidProductCateegoryParentId {
            get {
                return ResourceManager.GetString("Error_InValidProductCateegoryParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout was not successful....
        /// </summary>
        public static string Error_LogoutNotSuccessful {
            get {
                return ResourceManager.GetString("Error_LogoutNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model is null .
        /// </summary>
        public static string Error_ModelNull {
            get {
                return ResourceManager.GetString("Error_ModelNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order has not any details!.
        /// </summary>
        public static string Error_OrderNoDetails {
            get {
                return ResourceManager.GetString("Error_OrderNoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid productcategory.
        /// </summary>
        public static string Error_ProductCategoryNotFound {
            get {
                return ResourceManager.GetString("Error_ProductCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of products are duplicate!.
        /// </summary>
        public static string Error_ProductDuplicate {
            get {
                return ResourceManager.GetString("Error_ProductDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found!.
        /// </summary>
        public static string Error_RoleNotFound {
            get {
                return ResourceManager.GetString("Error_RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Seller and The buyer can not be same person.
        /// </summary>
        public static string Error_SameSelleAndBuyer {
            get {
                return ResourceManager.GetString("Error_SameSelleAndBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is null.
        /// </summary>
        public static string Error_TheParameterIsNull {
            get {
                return ResourceManager.GetString("Error_TheParameterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is mandatory.
        /// </summary>
        public static string Error_ThisFieldIsMandatory {
            get {
                return ResourceManager.GetString("Error_ThisFieldIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is duplicate.
        /// </summary>
        public static string Error_UserDuplicate {
            get {
                return ResourceManager.GetString("Error_UserDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has this role!.
        /// </summary>
        public static string Error_UserInRole {
            get {
                return ResourceManager.GetString("Error_UserInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found!.
        /// </summary>
        public static string Error_UserNotFound {
            get {
                return ResourceManager.GetString("Error_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has not any role.
        /// </summary>
        public static string Error_UserWithoutRole {
            get {
                return ResourceManager.GetString("Error_UserWithoutRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password Is not correct.
        /// </summary>
        public static string Error_WrongPassword {
            get {
                return ResourceManager.GetString("Error_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object is final, you can&apos;t delete it.
        /// </summary>
        public static string Finalobject {
            get {
                return ResourceManager.GetString("Finalobject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout was successful....
        /// </summary>
        public static string Info_LogoutSuccessFul {
            get {
                return ResourceManager.GetString("Info_LogoutSuccessFul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signingout was successfull..
        /// </summary>
        public static string Info_SignoutSuccessFull {
            get {
                return ResourceManager.GetString("Info_SignoutSuccessFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process was Successfull.
        /// </summary>
        public static string Info_SuccessfullProcess {
            get {
                return ResourceManager.GetString("Info_SuccessfullProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is uniq.
        /// </summary>
        public static string Info_UniqUser {
            get {
                return ResourceManager.GetString("Info_UniqUser", resourceCulture);
            }
        }
    }
}
